language: c
os: linux
dist: bionic

jobs:
  include:
    - os: linux
      env:
        - SETUP="x86_64-nogui"
    - os: linux
      env:
        - SETUP="x86_64"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
      - "nasm"
      - "grub-pc"


script:
  ci/build.sh ${SETUP}

install:
  ci/install.sh



before_deploy:
  - git config --local user.name "Antonino Natale"
  - git config --local user.email "antonio.natale97@hotmail.com"
  - export TRAVIS_TAG=v0.6.$(date +'%Y%m%d')
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token:
    "$GH_TOKEN"
    
  file: 
    - aplus-release-${SETUP}.tar.xz

  overwrite: true
  draft: false
  file_glob: true
  edge: true

  on:
    repo: kwrx/aplus-beta
    tags: false
